version: "3.9"
services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - frontend
    volumes:
      - wordpress_s:/var/www/html
    environment:
      SERVER_NAME: ${DOMAIN_NAME}

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wordpress_s:/var/www/html
    networks:
      - frontend
      - backend
    environment:
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_ADMIN_NAME: ${WORDPRESS_ADMIN_NAME}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_USER_NAME: ${WORDPRESS_USER_NAME}
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL}
      WORDPRESS_USER_PASSWORD: ${WORDPRESS_USER_PASSWORD}

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_d:/var/lib/mysql
    networks:
      - backend

volumes:
  wordpress_s:
    driver_opts:
        type: none
        device: /home/${LOGIN}/data/wordpress
        o: bind
  db_d:
    driver_opts:
        type: none
        device: /home/${LOGIN}/data/db
        o: bind

networks:
  frontend:
  backend:
